#!/usr/bin/env python


from circuits.web import Server, Controller
import os


class Root(Controller):

    def index(self):
        if os.environ.has_key('MSG'):
            return os.getenv('MSG')
        return "Hello World!"


def main():
    (Server(("0.0.0.0", 80)) + Root()).run()


if __name__ == "__main__":
    main()
